### ISSUE TITLE
[feat] post color case, image case 레이아웃 제작

### ISSUE THREAD

**Issue by kanglocal** [555team/rolling#10]
**📝 DESCRIBE**
post color case, image case 레이아웃 제작

**✅ TODO**
- [x] post color case 레이아웃 제작
- [x] post image case 레이아웃 제작
- [x] submit 기능 구현
