### ISSUE TITLE
[refactor] list 페이지 리팩토링할 부분 

### ISSUE THREAD

**Issue by olseul** [555team/rolling#67]
**📝 DESCRIBE**
- list 페이지 리팩토링 할 점들 모아놨습니다.

**✅ TODO**

- [x] userequest hook사용
- [x] 인기 롤링 페이퍼는 리액션 순으로 정렬하기
- [x] 화면 상단 margin값 줄이기
- [x] 반응형 tablet, mobile 터치 좌우 스크롤
- [x] '나도 만들어보기' 버튼을 클릭하면 /post 페이지로 이동
- [x] 생성된 카드를 클릭하면 /post{id} 페이지로 이동
- [x] 카드 배경이 색상만 받아오는데, 따로 이미지url을 지정한 경우 url을 받아오기, 이미지 url일 경우 폰트 색상 하얀색으로 변경
- [x] 카드 컴포넌트 마지막 페이지에서 가운데 정렬됨 -> 왼쪽 정렬로 수정
- [x] 프로필 컴포넌트, 리액션 컴포넌트 완성 시 결합

**💬 ETC**
기타사항
