### ISSUE TITLE
[refactor] 모달 컴포넌트 수정할 부분

### ISSUE THREAD

**Issue by hongjw030** [555team/rolling#70]
**📝 DESCRIBE**
모달 컴포넌트 기능적으론 문제 없지만 짜잘한 디자인 수정할 게 있어 이슈 올립니당

**✅ TODO**

- [x] 스크롤바 커스텀하기
- [x] ModalContainer 컴포넌트 분리하기
- [x] relationship에 따른 Badge 컴포넌트 코드 수정하기
- [x] 사용자 이미지가 없을 경우에 보여줄 no profile img 만들어오기
- [x] Card 컴포넌트 수정사항 있으면 팔로업해서 주기적으로.. 신속하게 모달 컴포넌트도 수정하기..   

**💬 ETC**
기타사항

**Comment by wecaners** [comment]
@Hongjw030 edit 페이지에서 휴지통 버튼 클릭하면 삭제되는데 그때 모달창이 같이 팝업 되는거같아요! 그리고 cursor pointer 속성 줘서 클릭할 수 있는 요소라는걸 알려주면 좋을 것 같습니다!

**Comment by hongjw030** [comment]
아~!!!! 코멘트 감사합니다!!!!!! 이따 cursor pointer 속성 넣어보겠습니다!!!!!
