### ISSUE TITLE
[UI] postPage 레이아웃 작성

### ISSUE THREAD

**Issue by wecaners** [555team/rolling#8]
**📝 DESCRIBE**
- postPage 레이아웃 작성
- 동적 라우팅 작성
- 반응형 디자인 구현

**✅ TODO**
- [x] postPage 레이아웃 작성
- [x] 동적 라우팅 구현
- [X] 반응형 디자인 구현

**💬 ETC**
기타사항
