### ISSUE TITLE
[refactor] 폰트 리팩토링하기 

### ISSUE THREAD

**Issue by hongjw030** [555team/rolling#90]
**📝 DESCRIBE**
폰트 최적화 할 것.

**✅ TODO**
- [x] 필요없는 weigth 폰트는 삭제. 저희가 쓰고 있는  weight가 400, 500, 700, 800 4개라서 이거 제외하곤 나머지 Noto Sans KR은 삭제하겠습니다. 
- [x] font-display 속성 추가
- [x] 힌팅 속성 추가
- [x] globalStyles.js에서 baseFont 값을 body로 옮길 것. 

**💬 ETC**
기타사항
